//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessScope complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessScope">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TypeCode" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessScopeTypeCode"/>
 *         &lt;element name="InstanceID" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessScopeInstanceID" minOccurs="0"/>
 *         &lt;element name="ID" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessScopeID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessScope", propOrder = {
    "typeCode",
    "instanceID",
    "id"
})
public class BusinessScope {

    @XmlElement(name = "TypeCode", required = true)
    protected BusinessScopeTypeCode typeCode;
    @XmlElement(name = "InstanceID")
    protected BusinessScopeInstanceID instanceID;
    @XmlElement(name = "ID")
    protected BusinessScopeID id;

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessScopeTypeCode }
     *     
     */
    public BusinessScopeTypeCode getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessScopeTypeCode }
     *     
     */
    public void setTypeCode(BusinessScopeTypeCode value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessScopeInstanceID }
     *     
     */
    public BusinessScopeInstanceID getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessScopeInstanceID }
     *     
     */
    public void setInstanceID(BusinessScopeInstanceID value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessScopeID }
     *     
     */
    public BusinessScopeID getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessScopeID }
     *     
     */
    public void setID(BusinessScopeID value) {
        this.id = value;
    }

}
