//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateConfirmationJournalEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateConfirmationJournalEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountingDocument" type="{http://sap.com/xi/SAPSCORE/SFIN}AccountingDocument"/>
 *         &lt;element name="CompanyCode" type="{http://sap.com/xi/SAPSCORE/SFIN}CompanyCodeID"/>
 *         &lt;element name="FiscalYear" type="{http://sap.com/xi/SAPSCORE/SFIN}FiscalYearID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateConfirmationJournalEntry", propOrder = {
    "accountingDocument",
    "companyCode",
    "fiscalYear"
})
public class JournalEntryCreateConfirmationJournalEntry {

    @XmlElement(name = "AccountingDocument", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String accountingDocument;
    @XmlElement(name = "CompanyCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String companyCode;
    @XmlElement(name = "FiscalYear", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fiscalYear;

    /**
     * Gets the value of the accountingDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingDocument() {
        return accountingDocument;
    }

    /**
     * Sets the value of the accountingDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingDocument(String value) {
        this.accountingDocument = value;
    }

    /**
     * Gets the value of the companyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * Sets the value of the companyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCode(String value) {
        this.companyCode = value;
    }

    /**
     * Gets the value of the fiscalYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiscalYear() {
        return fiscalYear;
    }

    /**
     * Sets the value of the fiscalYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiscalYear(String value) {
        this.fiscalYear = value;
    }

}
