//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryItemAccountAssignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryItemAccountAssignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountAssignmentType" type="{http://sap.com/xi/SAPSCORE/SFIN}AccountAssignmentType" minOccurs="0"/>
 *         &lt;element name="ProfitCenter" type="{http://sap.com/xi/SAPSCORE/SFIN}ProfitCentreID" minOccurs="0"/>
 *         &lt;element name="PartnerProfitCenter" type="{http://sap.com/xi/SAPSCORE/SFIN}ProfitCentreID" minOccurs="0"/>
 *         &lt;element name="Segment" type="{http://sap.com/xi/SAPSCORE/SFIN}SegmentID" minOccurs="0"/>
 *         &lt;element name="PartnerSegment" type="{http://sap.com/xi/SAPSCORE/SFIN}SegmentID" minOccurs="0"/>
 *         &lt;element name="CostCenter" type="{http://sap.com/xi/SAPSCORE/SFIN}CostCentreID" minOccurs="0"/>
 *         &lt;element name="CostCtrActivityType" type="{http://sap.com/xi/SAPSCORE/SFIN}ResourceClassID" minOccurs="0"/>
 *         &lt;element name="WBSElement" type="{http://sap.com/xi/SAPSCORE/SFIN}WBSElement" minOccurs="0"/>
 *         &lt;element name="MasterFixedAsset" type="{http://sap.com/xi/SAPSCORE/SFIN}MasterFixedAssetID" minOccurs="0"/>
 *         &lt;element name="FixedAsset" type="{http://sap.com/xi/SAPSCORE/SFIN}FixedAssetID" minOccurs="0"/>
 *         &lt;element name="SalesOrder" type="{http://sap.com/xi/SAPSCORE/SFIN}SalesOrder" minOccurs="0"/>
 *         &lt;element name="SalesOrderItem" type="{http://sap.com/xi/SAPSCORE/SFIN}SalesOrderItem" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryItemAccountAssignment", propOrder = {
    "accountAssignmentType",
    "profitCenter",
    "partnerProfitCenter",
    "segment",
    "partnerSegment",
    "costCenter",
    "costCtrActivityType",
    "wbsElement",
    "masterFixedAsset",
    "fixedAsset",
    "salesOrder",
    "salesOrderItem"
})
public class JournalEntryCreateRequestJournalEntryItemAccountAssignment {

    @XmlElement(name = "AccountAssignmentType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String accountAssignmentType;
    @XmlElement(name = "ProfitCenter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String profitCenter;
    @XmlElement(name = "PartnerProfitCenter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String partnerProfitCenter;
    @XmlElement(name = "Segment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;
    @XmlElement(name = "PartnerSegment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String partnerSegment;
    @XmlElement(name = "CostCenter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String costCenter;
    @XmlElement(name = "CostCtrActivityType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String costCtrActivityType;
    @XmlElement(name = "WBSElement")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String wbsElement;
    @XmlElement(name = "MasterFixedAsset")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String masterFixedAsset;
    @XmlElement(name = "FixedAsset")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fixedAsset;
    @XmlElement(name = "SalesOrder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String salesOrder;
    @XmlElement(name = "SalesOrderItem")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String salesOrderItem;

    /**
     * Gets the value of the accountAssignmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountAssignmentType() {
        return accountAssignmentType;
    }

    /**
     * Sets the value of the accountAssignmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountAssignmentType(String value) {
        this.accountAssignmentType = value;
    }

    /**
     * Gets the value of the profitCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfitCenter() {
        return profitCenter;
    }

    /**
     * Sets the value of the profitCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfitCenter(String value) {
        this.profitCenter = value;
    }

    /**
     * Gets the value of the partnerProfitCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerProfitCenter() {
        return partnerProfitCenter;
    }

    /**
     * Sets the value of the partnerProfitCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerProfitCenter(String value) {
        this.partnerProfitCenter = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment(String value) {
        this.segment = value;
    }

    /**
     * Gets the value of the partnerSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerSegment() {
        return partnerSegment;
    }

    /**
     * Sets the value of the partnerSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerSegment(String value) {
        this.partnerSegment = value;
    }

    /**
     * Gets the value of the costCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenter() {
        return costCenter;
    }

    /**
     * Sets the value of the costCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenter(String value) {
        this.costCenter = value;
    }

    /**
     * Gets the value of the costCtrActivityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCtrActivityType() {
        return costCtrActivityType;
    }

    /**
     * Sets the value of the costCtrActivityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCtrActivityType(String value) {
        this.costCtrActivityType = value;
    }

    /**
     * Gets the value of the wbsElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWBSElement() {
        return wbsElement;
    }

    /**
     * Sets the value of the wbsElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWBSElement(String value) {
        this.wbsElement = value;
    }

    /**
     * Gets the value of the masterFixedAsset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterFixedAsset() {
        return masterFixedAsset;
    }

    /**
     * Sets the value of the masterFixedAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterFixedAsset(String value) {
        this.masterFixedAsset = value;
    }

    /**
     * Gets the value of the fixedAsset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedAsset() {
        return fixedAsset;
    }

    /**
     * Sets the value of the fixedAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedAsset(String value) {
        this.fixedAsset = value;
    }

    /**
     * Gets the value of the salesOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrder() {
        return salesOrder;
    }

    /**
     * Sets the value of the salesOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrder(String value) {
        this.salesOrder = value;
    }

    /**
     * Gets the value of the salesOrderItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrderItem() {
        return salesOrderItem;
    }

    /**
     * Sets the value of the salesOrderItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrderItem(String value) {
        this.salesOrderItem = value;
    }

}
