//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryCreditorItemPaymentDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryCreditorItemPaymentDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentMethod" type="{http://sap.com/xi/SAPSCORE/SFIN}PaymentMethod" minOccurs="0"/>
 *         &lt;element name="PaymentMethodSupplement" type="{http://sap.com/xi/SAPSCORE/SFIN}PaymentMethodSupplement" minOccurs="0"/>
 *         &lt;element name="PaymentReference" type="{http://sap.com/xi/SAPSCORE/SFIN}PaymentReferenceID" minOccurs="0"/>
 *         &lt;element name="PaymentBlockingReason" type="{http://sap.com/xi/SAPSCORE/SFIN}PaymentBlockingReasonCode" minOccurs="0"/>
 *         &lt;element name="AlternativePayee" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessPartnerInternalID" minOccurs="0"/>
 *         &lt;element name="PayeeBankAccount" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryCreditorItemPaymentDetails", propOrder = {
    "paymentMethod",
    "paymentMethodSupplement",
    "paymentReference",
    "paymentBlockingReason",
    "alternativePayee",
    "payeeBankAccount"
})
public class JournalEntryCreateRequestJournalEntryCreditorItemPaymentDetails {

    @XmlElement(name = "PaymentMethod")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String paymentMethod;
    @XmlElement(name = "PaymentMethodSupplement")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String paymentMethodSupplement;
    @XmlElement(name = "PaymentReference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String paymentReference;
    @XmlElement(name = "PaymentBlockingReason")
    protected com.sap.xi.sapscore.sfin.PaymentBlockingReasonCode paymentBlockingReason;
    @XmlElement(name = "AlternativePayee")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String alternativePayee;
    @XmlElement(name = "PayeeBankAccount")
    protected JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount payeeBankAccount;

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethod(String value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the paymentMethodSupplement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethodSupplement() {
        return paymentMethodSupplement;
    }

    /**
     * Sets the value of the paymentMethodSupplement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethodSupplement(String value) {
        this.paymentMethodSupplement = value;
    }

    /**
     * Gets the value of the paymentReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentReference() {
        return paymentReference;
    }

    /**
     * Sets the value of the paymentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentReference(String value) {
        this.paymentReference = value;
    }

    /**
     * Gets the value of the paymentBlockingReason property.
     * 
     * @return
     *     possible object is
     *     {@link com.sap.xi.sapscore.sfin.PaymentBlockingReasonCode }
     *     
     */
    public com.sap.xi.sapscore.sfin.PaymentBlockingReasonCode getPaymentBlockingReason() {
        return paymentBlockingReason;
    }

    /**
     * Sets the value of the paymentBlockingReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sap.xi.sapscore.sfin.PaymentBlockingReasonCode }
     *     
     */
    public void setPaymentBlockingReason(PaymentBlockingReasonCode value) {
        this.paymentBlockingReason = value;
    }

    /**
     * Gets the value of the alternativePayee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternativePayee() {
        return alternativePayee;
    }

    /**
     * Sets the value of the alternativePayee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternativePayee(String value) {
        this.alternativePayee = value;
    }

    /**
     * Gets the value of the payeeBankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount }
     *     
     */
    public JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount getPayeeBankAccount() {
        return payeeBankAccount;
    }

    /**
     * Sets the value of the payeeBankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount }
     *     
     */
    public void setPayeeBankAccount(JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount value) {
        this.payeeBankAccount = value;
    }

}
