//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Customer" type="{http://sap.com/xi/SAPSCORE/SFIN}Customer" minOccurs="0"/>
 *         &lt;element name="CustomerGroup" type="{http://sap.com/xi/SAPSCORE/SFIN}CustomerGroupCode" minOccurs="0"/>
 *         &lt;element name="CustomerIndustry" type="{http://sap.com/xi/SAPSCORE/SFIN}IndustrialSectorCode" minOccurs="0"/>
 *         &lt;element name="CustomerCountry" type="{http://sap.com/xi/SAPSCORE/SFIN}CountryCode" minOccurs="0"/>
 *         &lt;element name="SalesDistrict" type="{http://sap.com/xi/SAPSCORE/SFIN}SalesDistrict" minOccurs="0"/>
 *         &lt;element name="SoldMaterial" type="{http://sap.com/xi/SAPSCORE/SFIN}Material" minOccurs="0"/>
 *         &lt;element name="SoldMaterialGroup" type="{http://sap.com/xi/SAPSCORE/SFIN}MaterialGroup" minOccurs="0"/>
 *         &lt;element name="SalesOrganization" type="{http://sap.com/xi/SAPSCORE/SFIN}SalesOrganization" minOccurs="0"/>
 *         &lt;element name="DistributionChannel" type="{http://sap.com/xi/SAPSCORE/SFIN}DistributionChannelCode" minOccurs="0"/>
 *         &lt;element name="Division" type="{http://sap.com/xi/SAPSCORE/SFIN}DivisionCode" minOccurs="0"/>
 *         &lt;element name="PersonnelNumber" type="{http://sap.com/xi/SAPSCORE/SFIN}PersonnelNumber_GFN" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement", propOrder = {
    "customer",
    "customerGroup",
    "customerIndustry",
    "customerCountry",
    "salesDistrict",
    "soldMaterial",
    "soldMaterialGroup",
    "salesOrganization",
    "distributionChannel",
    "division",
    "personnelNumber"
})
public class JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement {

    @XmlElement(name = "Customer")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String customer;
    @XmlElement(name = "CustomerGroup")
    protected com.sap.xi.sapscore.sfin.CustomerGroupCode customerGroup;
    @XmlElement(name = "CustomerIndustry")
    protected com.sap.xi.sapscore.sfin.IndustrialSectorCode customerIndustry;
    @XmlElement(name = "CustomerCountry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String customerCountry;
    @XmlElement(name = "SalesDistrict")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String salesDistrict;
    @XmlElement(name = "SoldMaterial")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String soldMaterial;
    @XmlElement(name = "SoldMaterialGroup")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String soldMaterialGroup;
    @XmlElement(name = "SalesOrganization")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String salesOrganization;
    @XmlElement(name = "DistributionChannel")
    protected com.sap.xi.sapscore.sfin.DistributionChannelCode distributionChannel;
    @XmlElement(name = "Division")
    protected com.sap.xi.sapscore.sfin.DivisionCode division;
    @XmlElement(name = "PersonnelNumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String personnelNumber;

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomer(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the customerGroup property.
     * 
     * @return
     *     possible object is
     *     {@link com.sap.xi.sapscore.sfin.CustomerGroupCode }
     *     
     */
    public com.sap.xi.sapscore.sfin.CustomerGroupCode getCustomerGroup() {
        return customerGroup;
    }

    /**
     * Sets the value of the customerGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sap.xi.sapscore.sfin.CustomerGroupCode }
     *     
     */
    public void setCustomerGroup(CustomerGroupCode value) {
        this.customerGroup = value;
    }

    /**
     * Gets the value of the customerIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link com.sap.xi.sapscore.sfin.IndustrialSectorCode }
     *     
     */
    public com.sap.xi.sapscore.sfin.IndustrialSectorCode getCustomerIndustry() {
        return customerIndustry;
    }

    /**
     * Sets the value of the customerIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sap.xi.sapscore.sfin.IndustrialSectorCode }
     *     
     */
    public void setCustomerIndustry(IndustrialSectorCode value) {
        this.customerIndustry = value;
    }

    /**
     * Gets the value of the customerCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCountry() {
        return customerCountry;
    }

    /**
     * Sets the value of the customerCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCountry(String value) {
        this.customerCountry = value;
    }

    /**
     * Gets the value of the salesDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesDistrict() {
        return salesDistrict;
    }

    /**
     * Sets the value of the salesDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesDistrict(String value) {
        this.salesDistrict = value;
    }

    /**
     * Gets the value of the soldMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldMaterial() {
        return soldMaterial;
    }

    /**
     * Sets the value of the soldMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldMaterial(String value) {
        this.soldMaterial = value;
    }

    /**
     * Gets the value of the soldMaterialGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoldMaterialGroup() {
        return soldMaterialGroup;
    }

    /**
     * Sets the value of the soldMaterialGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoldMaterialGroup(String value) {
        this.soldMaterialGroup = value;
    }

    /**
     * Gets the value of the salesOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesOrganization() {
        return salesOrganization;
    }

    /**
     * Sets the value of the salesOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesOrganization(String value) {
        this.salesOrganization = value;
    }

    /**
     * Gets the value of the distributionChannel property.
     * 
     * @return
     *     possible object is
     *     {@link com.sap.xi.sapscore.sfin.DistributionChannelCode }
     *     
     */
    public com.sap.xi.sapscore.sfin.DistributionChannelCode getDistributionChannel() {
        return distributionChannel;
    }

    /**
     * Sets the value of the distributionChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sap.xi.sapscore.sfin.DistributionChannelCode }
     *     
     */
    public void setDistributionChannel(DistributionChannelCode value) {
        this.distributionChannel = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link com.sap.xi.sapscore.sfin.DivisionCode }
     *     
     */
    public com.sap.xi.sapscore.sfin.DivisionCode getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sap.xi.sapscore.sfin.DivisionCode }
     *     
     */
    public void setDivision(DivisionCode value) {
        this.division = value;
    }

    /**
     * Gets the value of the personnelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonnelNumber() {
        return personnelNumber;
    }

    /**
     * Sets the value of the personnelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonnelNumber(String value) {
        this.personnelNumber = value;
    }

}
