//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JournalEntryCreateRequestBulkMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestBulkMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessDocumentMessageHeader"/>
 *         &lt;element name="JournalEntryCreateRequest" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestMessage" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestBulkMessage", propOrder = {
    "messageHeader",
    "journalEntryCreateRequest"
})
public class JournalEntryCreateRequestBulkMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected com.sap.xi.sapscore.sfin.BusinessDocumentMessageHeader messageHeader;
    @XmlElement(name = "JournalEntryCreateRequest", required = true)
    protected List<com.sap.xi.sapscore.sfin.JournalEntryCreateRequestMessage> journalEntryCreateRequest;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link com.sap.xi.sapscore.sfin.BusinessDocumentMessageHeader }
     *     
     */
    public com.sap.xi.sapscore.sfin.BusinessDocumentMessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sap.xi.sapscore.sfin.BusinessDocumentMessageHeader }
     *     
     */
    public void setMessageHeader(BusinessDocumentMessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the journalEntryCreateRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the journalEntryCreateRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJournalEntryCreateRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.sap.xi.sapscore.sfin.JournalEntryCreateRequestMessage }
     * 
     * 
     */
    public List<com.sap.xi.sapscore.sfin.JournalEntryCreateRequestMessage> getJournalEntryCreateRequest() {
        if (journalEntryCreateRequest == null) {
            journalEntryCreateRequest = new ArrayList<JournalEntryCreateRequestMessage>();
        }
        return this.journalEntryCreateRequest;
    }

}
