//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntryDebtorItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntryDebtorItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReferenceDocumentItem" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessTransactionDocumentItemID"/>
 *         &lt;element name="Debtor" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessPartnerInternalID"/>
 *         &lt;element name="AmountInTransactionCurrency" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount"/>
 *         &lt;element name="AmountInCompanyCodeCurrency" type="{http://sap.com/xi/SAPSCORE/SFIN}Amount" minOccurs="0"/>
 *         &lt;element name="DebitCreditCode" type="{http://sap.com/xi/SAPSCORE/SFIN}DebitCreditCode" minOccurs="0"/>
 *         &lt;element name="DocumentItemText" type="{http://sap.com/xi/SAPSCORE/SFIN}DocumentItemText" minOccurs="0"/>
 *         &lt;element name="AssignmentReference" type="{http://sap.com/xi/SAPSCORE/SFIN}AssignmentReference" minOccurs="0"/>
 *         &lt;element name="CashDiscountTerms" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestJournalEntryCashDiscountTerms" minOccurs="0"/>
 *         &lt;element name="PaymentDetails" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails" minOccurs="0"/>
 *         &lt;element name="StateCentralBankPaymentReason" type="{http://sap.com/xi/SAPSCORE/SFIN}StateCentralBankPaymentReason" minOccurs="0"/>
 *         &lt;element name="VATRegistration" type="{http://sap.com/xi/SAPSCORE/SFIN}VATRegistration" minOccurs="0"/>
 *         &lt;element name="BranchAccount" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessPartnerInternalID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntryDebtorItem", propOrder = {
    "referenceDocumentItem",
    "debtor",
    "amountInTransactionCurrency",
    "amountInCompanyCodeCurrency",
    "debitCreditCode",
    "documentItemText",
    "assignmentReference",
    "cashDiscountTerms",
    "paymentDetails",
    "stateCentralBankPaymentReason",
    "vatRegistration",
    "branchAccount"
})
public class JournalEntryCreateRequestJournalEntryDebtorItem {

    @XmlElement(name = "ReferenceDocumentItem", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String referenceDocumentItem;
    @XmlElement(name = "Debtor", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String debtor;
    @XmlElement(name = "AmountInTransactionCurrency", required = true)
    protected com.sap.xi.sapscore.sfin.Amount amountInTransactionCurrency;
    @XmlElement(name = "AmountInCompanyCodeCurrency")
    protected com.sap.xi.sapscore.sfin.Amount amountInCompanyCodeCurrency;
    @XmlElement(name = "DebitCreditCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String debitCreditCode;
    @XmlElement(name = "DocumentItemText")
    protected String documentItemText;
    @XmlElement(name = "AssignmentReference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String assignmentReference;
    @XmlElement(name = "CashDiscountTerms")
    protected JournalEntryCreateRequestJournalEntryCashDiscountTerms cashDiscountTerms;
    @XmlElement(name = "PaymentDetails")
    protected JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails paymentDetails;
    @XmlElement(name = "StateCentralBankPaymentReason")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stateCentralBankPaymentReason;
    @XmlElement(name = "VATRegistration")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String vatRegistration;
    @XmlElement(name = "BranchAccount")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String branchAccount;

    /**
     * Gets the value of the referenceDocumentItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceDocumentItem() {
        return referenceDocumentItem;
    }

    /**
     * Sets the value of the referenceDocumentItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceDocumentItem(String value) {
        this.referenceDocumentItem = value;
    }

    /**
     * Gets the value of the debtor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtor() {
        return debtor;
    }

    /**
     * Sets the value of the debtor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtor(String value) {
        this.debtor = value;
    }

    /**
     * Gets the value of the amountInTransactionCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link com.sap.xi.sapscore.sfin.Amount }
     *     
     */
    public com.sap.xi.sapscore.sfin.Amount getAmountInTransactionCurrency() {
        return amountInTransactionCurrency;
    }

    /**
     * Sets the value of the amountInTransactionCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sap.xi.sapscore.sfin.Amount }
     *     
     */
    public void setAmountInTransactionCurrency(com.sap.xi.sapscore.sfin.Amount value) {
        this.amountInTransactionCurrency = value;
    }

    /**
     * Gets the value of the amountInCompanyCodeCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link com.sap.xi.sapscore.sfin.Amount }
     *     
     */
    public com.sap.xi.sapscore.sfin.Amount getAmountInCompanyCodeCurrency() {
        return amountInCompanyCodeCurrency;
    }

    /**
     * Sets the value of the amountInCompanyCodeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sap.xi.sapscore.sfin.Amount }
     *     
     */
    public void setAmountInCompanyCodeCurrency(Amount value) {
        this.amountInCompanyCodeCurrency = value;
    }

    /**
     * Gets the value of the debitCreditCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitCreditCode() {
        return debitCreditCode;
    }

    /**
     * Sets the value of the debitCreditCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitCreditCode(String value) {
        this.debitCreditCode = value;
    }

    /**
     * Gets the value of the documentItemText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentItemText() {
        return documentItemText;
    }

    /**
     * Sets the value of the documentItemText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentItemText(String value) {
        this.documentItemText = value;
    }

    /**
     * Gets the value of the assignmentReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignmentReference() {
        return assignmentReference;
    }

    /**
     * Sets the value of the assignmentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignmentReference(String value) {
        this.assignmentReference = value;
    }

    /**
     * Gets the value of the cashDiscountTerms property.
     * 
     * @return
     *     possible object is
     *     {@link JournalEntryCreateRequestJournalEntryCashDiscountTerms }
     *     
     */
    public JournalEntryCreateRequestJournalEntryCashDiscountTerms getCashDiscountTerms() {
        return cashDiscountTerms;
    }

    /**
     * Sets the value of the cashDiscountTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalEntryCreateRequestJournalEntryCashDiscountTerms }
     *     
     */
    public void setCashDiscountTerms(JournalEntryCreateRequestJournalEntryCashDiscountTerms value) {
        this.cashDiscountTerms = value;
    }

    /**
     * Gets the value of the paymentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails }
     *     
     */
    public JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails getPaymentDetails() {
        return paymentDetails;
    }

    /**
     * Sets the value of the paymentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails }
     *     
     */
    public void setPaymentDetails(JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails value) {
        this.paymentDetails = value;
    }

    /**
     * Gets the value of the stateCentralBankPaymentReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCentralBankPaymentReason() {
        return stateCentralBankPaymentReason;
    }

    /**
     * Sets the value of the stateCentralBankPaymentReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCentralBankPaymentReason(String value) {
        this.stateCentralBankPaymentReason = value;
    }

    /**
     * Gets the value of the vatRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATRegistration() {
        return vatRegistration;
    }

    /**
     * Sets the value of the vatRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATRegistration(String value) {
        this.vatRegistration = value;
    }

    /**
     * Gets the value of the branchAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchAccount() {
        return branchAccount;
    }

    /**
     * Sets the value of the branchAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchAccount(String value) {
        this.branchAccount = value;
    }

}
