//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for JournalEntryCreateRequestJournalEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JournalEntryCreateRequestJournalEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OriginalReferenceDocumentType" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessTransactionDocumentTypeCode"/>
 *         &lt;element name="OriginalReferenceDocument" type="{http://sap.com/xi/SAPSCORE/SFIN}ReferenceDocumentID"/>
 *         &lt;element name="OriginalReferenceDocumentLogicalSystem" type="{http://sap.com/xi/SAPSCORE/SFIN}OriginalReferenceDocumentLogicalSystem"/>
 *         &lt;element name="BusinessTransactionType" type="{http://sap.com/xi/SAPSCORE/SFIN}AccountingBusinessTransactionTypeCode"/>
 *         &lt;element name="AccountingDocumentType" type="{http://sap.com/xi/SAPSCORE/SFIN}AccountingDocumentTypeCode"/>
 *         &lt;element name="DocumentReferenceID" type="{http://sap.com/xi/SAPSCORE/SFIN}DocumentReferenceID" minOccurs="0"/>
 *         &lt;element name="OriginalPredecessorRefDocument" type="{http://sap.com/xi/SAPSCORE/SFIN}ReferenceDocumentID" minOccurs="0"/>
 *         &lt;element name="DocumentHeaderText" type="{http://sap.com/xi/SAPSCORE/SFIN}DocumentHeaderText" minOccurs="0"/>
 *         &lt;element name="CreatedByUser" type="{http://sap.com/xi/SAPSCORE/SFIN}CreatedByUser"/>
 *         &lt;element name="CompanyCode" type="{http://sap.com/xi/SAPSCORE/SFIN}CompanyCodeID"/>
 *         &lt;element name="DocumentDate" type="{http://sap.com/xi/SAPSCORE/SFIN}Date"/>
 *         &lt;element name="PostingDate" type="{http://sap.com/xi/SAPSCORE/SFIN}Date"/>
 *         &lt;element name="TaxReportingDate" type="{http://sap.com/xi/SAPSCORE/SFIN}Date" minOccurs="0"/>
 *         &lt;element name="InvoiceReceiptDate" type="{http://sap.com/xi/SAPSCORE/SFIN}Date" minOccurs="0"/>
 *         &lt;element name="ExchangeRateDate" type="{http://sap.com/xi/SAPSCORE/SFIN}Date" minOccurs="0"/>
 *         &lt;element name="ExchangeRate" type="{http://sap.com/xi/SAPSCORE/SFIN}ExchangeRateRate" minOccurs="0"/>
 *         &lt;element name="SourceSystemCompanyCode" type="{http://sap.com/xi/SAPSCORE/SFIN}OrganisationalCentreID" minOccurs="0"/>
 *         &lt;element name="SourceSystemAccountingDocument" type="{http://sap.com/xi/SAPSCORE/SFIN}BusinessTransactionDocumentID" minOccurs="0"/>
 *         &lt;element name="Item" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestJournalEntryItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DebtorItem" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestJournalEntryDebtorItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreditorItem" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestJournalEntryCreditorItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProductTaxItem" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestJournalEntryProductTaxItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WithholdingTaxItem" type="{http://sap.com/xi/SAPSCORE/SFIN}JournalEntryCreateRequestJournalEntryWithholdingTaxItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JournalEntryCreateRequestJournalEntry", propOrder = {
    "originalReferenceDocumentType",
    "originalReferenceDocument",
    "originalReferenceDocumentLogicalSystem",
    "businessTransactionType",
    "accountingDocumentType",
    "documentReferenceID",
    "originalPredecessorRefDocument",
    "documentHeaderText",
    "createdByUser",
    "companyCode",
    "documentDate",
    "postingDate",
    "taxReportingDate",
    "invoiceReceiptDate",
    "exchangeRateDate",
    "exchangeRate",
    "sourceSystemCompanyCode",
    "sourceSystemAccountingDocument",
    "item",
    "debtorItem",
    "creditorItem",
    "productTaxItem",
    "withholdingTaxItem"
})
public class JournalEntryCreateRequestJournalEntry {

    @XmlElement(name = "OriginalReferenceDocumentType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originalReferenceDocumentType;
    @XmlElement(name = "OriginalReferenceDocument", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originalReferenceDocument;
    @XmlElement(name = "OriginalReferenceDocumentLogicalSystem", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originalReferenceDocumentLogicalSystem;
    @XmlElement(name = "BusinessTransactionType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String businessTransactionType;
    @XmlElement(name = "AccountingDocumentType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String accountingDocumentType;
    @XmlElement(name = "DocumentReferenceID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String documentReferenceID;
    @XmlElement(name = "OriginalPredecessorRefDocument")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originalPredecessorRefDocument;
    @XmlElement(name = "DocumentHeaderText")
    protected String documentHeaderText;
    @XmlElement(name = "CreatedByUser", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String createdByUser;
    @XmlElement(name = "CompanyCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String companyCode;
    @XmlElement(name = "DocumentDate", required = true)
    protected XMLGregorianCalendar documentDate;
    @XmlElement(name = "PostingDate", required = true)
    protected XMLGregorianCalendar postingDate;
    @XmlElement(name = "TaxReportingDate")
    protected XMLGregorianCalendar taxReportingDate;
    @XmlElement(name = "InvoiceReceiptDate")
    protected XMLGregorianCalendar invoiceReceiptDate;
    @XmlElement(name = "ExchangeRateDate")
    protected XMLGregorianCalendar exchangeRateDate;
    @XmlElement(name = "ExchangeRate")
    protected BigDecimal exchangeRate;
    @XmlElement(name = "SourceSystemCompanyCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sourceSystemCompanyCode;
    @XmlElement(name = "SourceSystemAccountingDocument")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sourceSystemAccountingDocument;
    @XmlElement(name = "Item")
    protected List<JournalEntryCreateRequestJournalEntryItem> item;
    @XmlElement(name = "DebtorItem")
    protected List<JournalEntryCreateRequestJournalEntryDebtorItem> debtorItem;
    @XmlElement(name = "CreditorItem")
    protected List<JournalEntryCreateRequestJournalEntryCreditorItem> creditorItem;
    @XmlElement(name = "ProductTaxItem")
    protected List<JournalEntryCreateRequestJournalEntryProductTaxItem> productTaxItem;
    @XmlElement(name = "WithholdingTaxItem")
    protected List<JournalEntryCreateRequestJournalEntryWithholdingTaxItem> withholdingTaxItem;

    /**
     * Gets the value of the originalReferenceDocumentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalReferenceDocumentType() {
        return originalReferenceDocumentType;
    }

    /**
     * Sets the value of the originalReferenceDocumentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalReferenceDocumentType(String value) {
        this.originalReferenceDocumentType = value;
    }

    /**
     * Gets the value of the originalReferenceDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalReferenceDocument() {
        return originalReferenceDocument;
    }

    /**
     * Sets the value of the originalReferenceDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalReferenceDocument(String value) {
        this.originalReferenceDocument = value;
    }

    /**
     * Gets the value of the originalReferenceDocumentLogicalSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalReferenceDocumentLogicalSystem() {
        return originalReferenceDocumentLogicalSystem;
    }

    /**
     * Sets the value of the originalReferenceDocumentLogicalSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalReferenceDocumentLogicalSystem(String value) {
        this.originalReferenceDocumentLogicalSystem = value;
    }

    /**
     * Gets the value of the businessTransactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessTransactionType() {
        return businessTransactionType;
    }

    /**
     * Sets the value of the businessTransactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessTransactionType(String value) {
        this.businessTransactionType = value;
    }

    /**
     * Gets the value of the accountingDocumentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingDocumentType() {
        return accountingDocumentType;
    }

    /**
     * Sets the value of the accountingDocumentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingDocumentType(String value) {
        this.accountingDocumentType = value;
    }

    /**
     * Gets the value of the documentReferenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentReferenceID() {
        return documentReferenceID;
    }

    /**
     * Sets the value of the documentReferenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentReferenceID(String value) {
        this.documentReferenceID = value;
    }

    /**
     * Gets the value of the originalPredecessorRefDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalPredecessorRefDocument() {
        return originalPredecessorRefDocument;
    }

    /**
     * Sets the value of the originalPredecessorRefDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalPredecessorRefDocument(String value) {
        this.originalPredecessorRefDocument = value;
    }

    /**
     * Gets the value of the documentHeaderText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentHeaderText() {
        return documentHeaderText;
    }

    /**
     * Sets the value of the documentHeaderText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentHeaderText(String value) {
        this.documentHeaderText = value;
    }

    /**
     * Gets the value of the createdByUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedByUser() {
        return createdByUser;
    }

    /**
     * Sets the value of the createdByUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedByUser(String value) {
        this.createdByUser = value;
    }

    /**
     * Gets the value of the companyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * Sets the value of the companyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCode(String value) {
        this.companyCode = value;
    }

    /**
     * Gets the value of the documentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocumentDate(XMLGregorianCalendar value) {
        this.documentDate = value;
    }

    /**
     * Gets the value of the postingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostingDate() {
        return postingDate;
    }

    /**
     * Sets the value of the postingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPostingDate(XMLGregorianCalendar value) {
        this.postingDate = value;
    }

    /**
     * Gets the value of the taxReportingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaxReportingDate() {
        return taxReportingDate;
    }

    /**
     * Sets the value of the taxReportingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaxReportingDate(XMLGregorianCalendar value) {
        this.taxReportingDate = value;
    }

    /**
     * Gets the value of the invoiceReceiptDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceReceiptDate() {
        return invoiceReceiptDate;
    }

    /**
     * Sets the value of the invoiceReceiptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceReceiptDate(XMLGregorianCalendar value) {
        this.invoiceReceiptDate = value;
    }

    /**
     * Gets the value of the exchangeRateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExchangeRateDate() {
        return exchangeRateDate;
    }

    /**
     * Sets the value of the exchangeRateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExchangeRateDate(XMLGregorianCalendar value) {
        this.exchangeRateDate = value;
    }

    /**
     * Gets the value of the exchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExchangeRate(BigDecimal value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the sourceSystemCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemCompanyCode() {
        return sourceSystemCompanyCode;
    }

    /**
     * Sets the value of the sourceSystemCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemCompanyCode(String value) {
        this.sourceSystemCompanyCode = value;
    }

    /**
     * Gets the value of the sourceSystemAccountingDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemAccountingDocument() {
        return sourceSystemAccountingDocument;
    }

    /**
     * Sets the value of the sourceSystemAccountingDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemAccountingDocument(String value) {
        this.sourceSystemAccountingDocument = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalEntryCreateRequestJournalEntryItem }
     * 
     * 
     */
    public List<JournalEntryCreateRequestJournalEntryItem> getItem() {
        if (item == null) {
            item = new ArrayList<JournalEntryCreateRequestJournalEntryItem>();
        }
        return this.item;
    }

    /**
     * Gets the value of the debtorItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the debtorItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDebtorItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalEntryCreateRequestJournalEntryDebtorItem }
     * 
     * 
     */
    public List<JournalEntryCreateRequestJournalEntryDebtorItem> getDebtorItem() {
        if (debtorItem == null) {
            debtorItem = new ArrayList<JournalEntryCreateRequestJournalEntryDebtorItem>();
        }
        return this.debtorItem;
    }

    /**
     * Gets the value of the creditorItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditorItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditorItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalEntryCreateRequestJournalEntryCreditorItem }
     * 
     * 
     */
    public List<JournalEntryCreateRequestJournalEntryCreditorItem> getCreditorItem() {
        if (creditorItem == null) {
            creditorItem = new ArrayList<JournalEntryCreateRequestJournalEntryCreditorItem>();
        }
        return this.creditorItem;
    }

    /**
     * Gets the value of the productTaxItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productTaxItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductTaxItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalEntryCreateRequestJournalEntryProductTaxItem }
     * 
     * 
     */
    public List<JournalEntryCreateRequestJournalEntryProductTaxItem> getProductTaxItem() {
        if (productTaxItem == null) {
            productTaxItem = new ArrayList<JournalEntryCreateRequestJournalEntryProductTaxItem>();
        }
        return this.productTaxItem;
    }

    /**
     * Gets the value of the withholdingTaxItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the withholdingTaxItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWithholdingTaxItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JournalEntryCreateRequestJournalEntryWithholdingTaxItem }
     * 
     * 
     */
    public List<JournalEntryCreateRequestJournalEntryWithholdingTaxItem> getWithholdingTaxItem() {
        if (withholdingTaxItem == null) {
            withholdingTaxItem = new ArrayList<JournalEntryCreateRequestJournalEntryWithholdingTaxItem>();
        }
        return this.withholdingTaxItem;
    }

}
