//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//


package com.sap.xi.sapscore.sfin;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sap.xi.sapscore.sfin package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _JournalEntryBulkCreateRequest_QNAME = new QName("http://sap.com/xi/SAPSCORE/SFIN", "JournalEntryBulkCreateRequest");
    private final static QName _JournalEntryBulkCreateConfirmation_QNAME = new QName("http://sap.com/xi/SAPSCORE/SFIN", "JournalEntryBulkCreateConfirmation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sap.xi.sapscore.sfin
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryDebtorItem }
     * 
     */
    public JournalEntryCreateRequestJournalEntryDebtorItem createJournalEntryCreateRequestJournalEntryDebtorItem() {
        return new JournalEntryCreateRequestJournalEntryDebtorItem();
    }

    /**
     * Create an instance of {@link TaxJurisdictionCode }
     * 
     */
    public TaxJurisdictionCode createTaxJurisdictionCode() {
        return new TaxJurisdictionCode();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.PhoneNumber }
     * 
     */
    public com.sap.xi.sapscore.sfin.PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.Quantity }
     * 
     */
    public com.sap.xi.sapscore.sfin.Quantity createQuantity() {
        return new Quantity();
    }

    /**
     * Create an instance of {@link LogItemNotePlaceholderSubstitutionList }
     * 
     */
    public LogItemNotePlaceholderSubstitutionList createLogItemNotePlaceholderSubstitutionList() {
        return new LogItemNotePlaceholderSubstitutionList();
    }

    /**
     * Create an instance of {@link BusinessDocumentMessageHeaderParty }
     * 
     */
    public BusinessDocumentMessageHeaderParty createBusinessDocumentMessageHeaderParty() {
        return new BusinessDocumentMessageHeaderParty();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount }
     * 
     */
    public JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount createJournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount() {
        return new JournalEntryCreateRequestJournalEntryCreditorItemPayeeBankAccount();
    }

    /**
     * Create an instance of {@link IndustrialSectorCode }
     * 
     */
    public IndustrialSectorCode createIndustrialSectorCode() {
        return new IndustrialSectorCode();
    }

    /**
     * Create an instance of {@link DistributionChannelCode }
     * 
     */
    public DistributionChannelCode createDistributionChannelCode() {
        return new DistributionChannelCode();
    }

    /**
     * Create an instance of {@link PartyInternalID }
     * 
     */
    public PartyInternalID createPartyInternalID() {
        return new PartyInternalID();
    }

    /**
     * Create an instance of {@link BusinessScopeTypeCode }
     * 
     */
    public BusinessScopeTypeCode createBusinessScopeTypeCode() {
        return new BusinessScopeTypeCode();
    }

    /**
     * Create an instance of {@link BusinessScopeInstanceID }
     * 
     */
    public BusinessScopeInstanceID createBusinessScopeInstanceID() {
        return new BusinessScopeInstanceID();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.DivisionCode }
     * 
     */
    public com.sap.xi.sapscore.sfin.DivisionCode createDivisionCode() {
        return new DivisionCode();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryItem }
     * 
     */
    public JournalEntryCreateRequestJournalEntryItem createJournalEntryCreateRequestJournalEntryItem() {
        return new JournalEntryCreateRequestJournalEntryItem();
    }

    /**
     * Create an instance of {@link LogItemCategoryCode }
     * 
     */
    public LogItemCategoryCode createLogItemCategoryCode() {
        return new LogItemCategoryCode();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntry }
     * 
     */
    public JournalEntryCreateRequestJournalEntry createJournalEntryCreateRequestJournalEntry() {
        return new JournalEntryCreateRequestJournalEntry();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryCreditorItem }
     * 
     */
    public JournalEntryCreateRequestJournalEntryCreditorItem createJournalEntryCreateRequestJournalEntryCreditorItem() {
        return new JournalEntryCreateRequestJournalEntryCreditorItem();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails }
     * 
     */
    public JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails createJournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails() {
        return new JournalEntryCreateRequestJournalEntryDebtorItemPaymentDetails();
    }

    /**
     * Create an instance of {@link ChartOfAccountsItemCode }
     * 
     */
    public ChartOfAccountsItemCode createChartOfAccountsItemCode() {
        return new ChartOfAccountsItemCode();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryWithholdingTaxItem }
     * 
     */
    public JournalEntryCreateRequestJournalEntryWithholdingTaxItem createJournalEntryCreateRequestJournalEntryWithholdingTaxItem() {
        return new JournalEntryCreateRequestJournalEntryWithholdingTaxItem();
    }

    /**
     * Create an instance of {@link BusinessDocumentMessageID }
     * 
     */
    public BusinessDocumentMessageID createBusinessDocumentMessageID() {
        return new BusinessDocumentMessageID();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.BusinessScope }
     * 
     */
    public com.sap.xi.sapscore.sfin.BusinessScope createBusinessScope() {
        return new BusinessScope();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryTaxDetails }
     * 
     */
    public JournalEntryCreateRequestJournalEntryTaxDetails createJournalEntryCreateRequestJournalEntryTaxDetails() {
        return new JournalEntryCreateRequestJournalEntryTaxDetails();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.LogItem }
     * 
     */
    public com.sap.xi.sapscore.sfin.LogItem createLogItem() {
        return new LogItem();
    }

    /**
     * Create an instance of {@link PartyStandardID }
     * 
     */
    public PartyStandardID createPartyStandardID() {
        return new PartyStandardID();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.EmailURI }
     * 
     */
    public com.sap.xi.sapscore.sfin.EmailURI createEmailURI() {
        return new EmailURI();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryCashDiscountTerms }
     * 
     */
    public JournalEntryCreateRequestJournalEntryCashDiscountTerms createJournalEntryCreateRequestJournalEntryCashDiscountTerms() {
        return new JournalEntryCreateRequestJournalEntryCashDiscountTerms();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.Log }
     * 
     */
    public com.sap.xi.sapscore.sfin.Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryCreditorItemPaymentDetails }
     * 
     */
    public JournalEntryCreateRequestJournalEntryCreditorItemPaymentDetails createJournalEntryCreateRequestJournalEntryCreditorItemPaymentDetails() {
        return new JournalEntryCreateRequestJournalEntryCreditorItemPaymentDetails();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.Amount }
     * 
     */
    public com.sap.xi.sapscore.sfin.Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link BusinessDocumentMessageHeaderPartyContactPerson }
     * 
     */
    public BusinessDocumentMessageHeaderPartyContactPerson createBusinessDocumentMessageHeaderPartyContactPerson() {
        return new BusinessDocumentMessageHeaderPartyContactPerson();
    }

    /**
     * Create an instance of {@link ContactPersonInternalID }
     * 
     */
    public ContactPersonInternalID createContactPersonInternalID() {
        return new ContactPersonInternalID();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.MEDIUMName }
     * 
     */
    public com.sap.xi.sapscore.sfin.MEDIUMName createMEDIUMName() {
        return new MEDIUMName();
    }

    /**
     * Create an instance of {@link JournalEntryCreateConfirmationMessage }
     * 
     */
    public JournalEntryCreateConfirmationMessage createJournalEntryCreateConfirmationMessage() {
        return new JournalEntryCreateConfirmationMessage();
    }

    /**
     * Create an instance of {@link CustomerGroupCode }
     * 
     */
    public CustomerGroupCode createCustomerGroupCode() {
        return new CustomerGroupCode();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestBulkMessage }
     * 
     */
    public JournalEntryCreateRequestBulkMessage createJournalEntryCreateRequestBulkMessage() {
        return new JournalEntryCreateRequestBulkMessage();
    }

    /**
     * Create an instance of {@link JournalEntryCreateConfirmationBulkMessage }
     * 
     */
    public JournalEntryCreateConfirmationBulkMessage createJournalEntryCreateConfirmationBulkMessage() {
        return new JournalEntryCreateConfirmationBulkMessage();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryItemAccountAssignment }
     * 
     */
    public JournalEntryCreateRequestJournalEntryItemAccountAssignment createJournalEntryCreateRequestJournalEntryItemAccountAssignment() {
        return new JournalEntryCreateRequestJournalEntryItemAccountAssignment();
    }

    /**
     * Create an instance of {@link ProductTaxationCharacteristicsCode }
     * 
     */
    public ProductTaxationCharacteristicsCode createProductTaxationCharacteristicsCode() {
        return new ProductTaxationCharacteristicsCode();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestMessage }
     * 
     */
    public JournalEntryCreateRequestMessage createJournalEntryCreateRequestMessage() {
        return new JournalEntryCreateRequestMessage();
    }

    /**
     * Create an instance of {@link BusinessDocumentMessageHeader }
     * 
     */
    public BusinessDocumentMessageHeader createBusinessDocumentMessageHeader() {
        return new BusinessDocumentMessageHeader();
    }

    /**
     * Create an instance of {@link PaymentBlockingReasonCode }
     * 
     */
    public PaymentBlockingReasonCode createPaymentBlockingReasonCode() {
        return new PaymentBlockingReasonCode();
    }

    /**
     * Create an instance of {@link JournalEntryCreateConfirmationJournalEntry }
     * 
     */
    public JournalEntryCreateConfirmationJournalEntry createJournalEntryCreateConfirmationJournalEntry() {
        return new JournalEntryCreateConfirmationJournalEntry();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement }
     * 
     */
    public JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement createJournalEntryCreateRequestJournalEntryItemProfitabilitySupplement() {
        return new JournalEntryCreateRequestJournalEntryItemProfitabilitySupplement();
    }

    /**
     * Create an instance of {@link com.sap.xi.sapscore.sfin.UUID }
     * 
     */
    public com.sap.xi.sapscore.sfin.UUID createUUID() {
        return new UUID();
    }

    /**
     * Create an instance of {@link JournalEntryCreateRequestJournalEntryProductTaxItem }
     * 
     */
    public JournalEntryCreateRequestJournalEntryProductTaxItem createJournalEntryCreateRequestJournalEntryProductTaxItem() {
        return new JournalEntryCreateRequestJournalEntryProductTaxItem();
    }

    /**
     * Create an instance of {@link BusinessScopeID }
     * 
     */
    public BusinessScopeID createBusinessScopeID() {
        return new BusinessScopeID();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JournalEntryCreateRequestBulkMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sap.com/xi/SAPSCORE/SFIN", name = "JournalEntryBulkCreateRequest")
    public JAXBElement<JournalEntryCreateRequestBulkMessage> createJournalEntryBulkCreateRequest(JournalEntryCreateRequestBulkMessage value) {
        return new JAXBElement<JournalEntryCreateRequestBulkMessage>(_JournalEntryBulkCreateRequest_QNAME, JournalEntryCreateRequestBulkMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JournalEntryCreateConfirmationBulkMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sap.com/xi/SAPSCORE/SFIN", name = "JournalEntryBulkCreateConfirmation")
    public JAXBElement<JournalEntryCreateConfirmationBulkMessage> createJournalEntryBulkCreateConfirmation(JournalEntryCreateConfirmationBulkMessage value) {
        return new JAXBElement<JournalEntryCreateConfirmationBulkMessage>(_JournalEntryBulkCreateConfirmation_QNAME, JournalEntryCreateConfirmationBulkMessage.class, null, value);
    }

}
