//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 10:52:02 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sap.com/xi/SAPSCORE/SFIN")
package com.sap.xi.sapscore.sfin;
